config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :product_tags
  resources :product_details
 
  get 'tag_creation/Tag_setup'

  # For#Get details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root 'tag_creation#Tag_setup'
 root 'product_tags#new'
 
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:shopify_account_url, :shopify_api_key, :shopify_password, :shopify_shared_secret)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_tags_controller.rb
class ProductTagsController < ApplicationController
  before_action :set_product_tag, only: [:show, :edit, :update, :destroy]

  # GET /product_tags
  # GET /product_tags.json
  def index
    @product_tags = ProductTag.all
  end

  # GET /product_tags/1
  # GET /product_tags/1.json
  def show
  end

  # GET /product_tags/new
  def new
    @product_tag = ProductTag.new
  end

  # GET /product_tags/1/edit
  def edit
  end

  # POST /product_tags
  # POST /product_tags.json
  def create
    @product_tag = ProductTag.new(product_tag_params)

    respond_to do |format|
      if @product_tag.save
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully created.' }
        format.json { render :show, status: :created, location: @product_tag }
      else
        format.html { render :new }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_tags/1
  # PATCH/PUT /product_tags/1.json
  def update
    respond_to do |format|
      if @product_tag.update(product_tag_params)
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_tag }
      else
        format.html { render :edit }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_tags/1
  # DELETE /product_tags/1.json
  def destroy
    @product_tag.destroy
    respond_to do |format|
      format.html { redirect_to product_tags_url, notice: 'Product tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_tag
      @product_tag = ProductTag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_tag_params
      params.require(:product_tag).permit(:pid, :pcategory, :pgroup, :pcode, :pdescription, :ptag)
    end
end

app/controllers/tag_creation_controller.rb
class TagCreationController < ApplicationController
  def Tag_setup
  end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_details_helper.rb
module ProductDetailsHelper
end

app/helpers/product_tags_helper.rb
module ProductTagsHelper
end

app/helpers/tag_creation_helper.rb
module TagCreationHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => "form-horizontal account" } do |f| %>

  <% if @account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :shopify_account_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_account_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_account_url) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_api_key, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_api_key, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_api_key) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_password) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_shared_secret, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_shared_secret, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_shared_secret) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:shopify_account_url) %></th>
      <th><%= model_class.human_attribute_name(:shopify_api_key) %></th>
      <th><%= model_class.human_attribute_name(:shopify_password) %></th>
      <th><%= model_class.human_attribute_name(:shopify_shared_secret) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.shopify_account_url %></td>
        <td><%= account.shopify_api_key %></td>
        <td><%= account.shopify_password %></td>
        <td><%= account.shopify_shared_secret %></td>
        <td><%=l account.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:shopify_account_url) %>:</strong></dt>
  <dd><%= @account.shopify_account_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_api_key) %>:</strong></dt>
  <dd><%= @account.shopify_api_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_password) %>:</strong></dt>
  <dd><%= @account.shopify_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_shared_secret) %>:</strong></dt>
  <dd><%= @account.shopify_shared_secret %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PvtShopifyApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' , :skip_pipeline => 'true' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' , :skip_pipeline => 'true' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' , :skip_pipeline => 'true' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' ,:skip_pipeline=> 'true' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' , :skip_pipeline => 'true' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="https://www.shopify.in/">ShopifyApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Search in Google", "https://www.google.com/"  %></li>
            
          </ul>
          <h1><center>TagCreation</center></h1>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Suggested Tags</h3>
            <ul class="nav nav-list">
                     <li><%= link_to "Tag", "/path1"  %></li>
              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Spr 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/product_details/_form.html.erb
<%= form_with(model: product_detail, local: true) do |form| %>
  <% if product_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_detail.errors.count, "error") %> prohibited this product_detail from being saved:</h2>

      <ul>
      <% product_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productid %>
    <%= form.number_field :productid, id: :product_detail_productid %>
  </div>

  <div class="field">
    <%= form.label :productcategory %>
    <%= form.text_field :productcategory, id: :product_detail_productcategory %>
  </div>

  <div class="field">
    <%= form.label :productgroup %>
    <%= form.text_field :productgroup, id: :product_detail_productgroup %>
  </div>

  <div class="field">
    <%= form.label :productcode %>
    <%= form.text_field :productcode, id: :product_detail_productcode %>
  </div>

  <div class="field">
    <%= form.label :productdescription %>
    <%= form.text_field :productdescription, id: :product_detail_productdescription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_details/edit.html.erb
<h1>Editing Product Detail</h1>

<%= render 'form', product_detail: @product_detail %>

<%= link_to 'Show', @product_detail %> |
<%= link_to 'Back', product_details_path %>

app/views/product_details/index.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th>Productcategory</th>
      <th>Productgroup</th>
      <th>Productcode</th>
      <th>Productdescription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_details.each do |product_detail| %>
      <tr>
        <td><%= product_detail.productid %></td>
        <td><%= product_detail.productcategory %></td>
        <td><%= product_detail.productgroup %></td>
        <td><%= product_detail.productcode %></td>
        <td><%= product_detail.productdescription %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/product_details/new.html.erb
<h1>New Product Detail</h1>

<%= render 'form', product_detail: @product_detail %>

<%= link_to 'Back', product_details_path %>

app/views/product_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @product_detail.productid %>
</p>

<p>
  <strong>Productcategory:</strong>
  <%= @product_detail.productcategory %>
</p>

<p>
  <strong>Productgroup:</strong>
  <%= @product_detail.productgroup %>
</p>

<p>
  <strong>Productcode:</strong>
  <%= @product_detail.productcode %>
</p>

<p>
  <strong>Productdescription:</strong>
  <%= @product_detail.productdescription %>
</p>

<%= link_to 'Edit', edit_product_detail_path(@product_detail) %> |
<%= link_to 'Back', product_details_path %>

app/views/product_tags/_form.html.erb
<%= form_with(model: product_tag, local: true) do |form| %>
  <% if product_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_tag.errors.count, "error") %> prohibited this product_tag from being saved:</h2>

      <ul>
      <% product_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table border=1>
<tr>
  <td>  <%= form.label :Product_Item %></td><td><%= form.text_field :pid, id: :product_tag_pid %></td>
</tr>
<tr>
  <td>
   <%= form.label :Product_category %></td><td> <%= form.text_field :pcategory, id: :product_tag_pcategory %></td>
 </tr>
 <tr>
  <td><%= form.label :Product_group %>   </td><td> <%= form.text_field :pgroup, id: :product_tag_pgroup %></td>
</tr>
<tr> <td><%= form.label :Product_code %> </td><td> <%= form.text_field :pcode, id: :product_tag_pcode %></td>
</tr>
<tr>
      <td><%= form.label :Product_description %> </td><td>  <%= form.text_field :pdescription, id: :product_tag_pdescription %></td>
    </tr>
    <tr>
<td>   <%= form.label :Product_tag %>  </td><td>  <%= form.text_field :ptag, id: :product_tag_ptag %></td>
</tr>
  
<tr>
  <div class="classrow">
    
      
  </div>
</tr>
</table>
  <div class="actions" align="right">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_tags/edit.html.erb
<h1>Editing Product Tag</h1>

<%= render 'form', product_tag: @product_tag %>

<%= link_to 'Show', @product_tag %> |
<%= link_to 'Back', product_tags_path %>

app/views/product_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Tags</h1>

<table border=1>
  <thead>
    <tr>
      
      <th>ProductCategory</th>
      <th>ProductGroup</th>
      <th>ProductCode</th>
      <th>ProductDescription</th>
      <th>ProductTag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @product_tags.each do |product_tag| %>
      <tr>
        
        <td><%= product_tag.pcategory %></td>
        <td><%= product_tag.pgroup %></td>
        <td><%= product_tag.pcode %></td>
        <td><%= product_tag.pdescription %></td>
        <td><%= product_tag.ptag %></td>
        <!--<td><%= link_to 'Show', product_tag %></td> -->
       <!-- <td><%= link_to 'Edit', edit_product_tag_path(product_tag) %></td>-->
        <!--<td><%= link_to 'Destroy', product_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Tag', new_product_tag_path %>

app/views/product_tags/new.html.erb
<h1>New Product Tag</h1>

<%= render 'form', product_tag: @product_tag %>

<%= link_to 'Back', product_tags_path %>

app/views/product_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @product_tag.pid %>
</p>

<p>
  <strong>Pcategory:</strong>
  <%= @product_tag.pcategory %>
</p>

<p>
  <strong>Pgroup:</strong>
  <%= @product_tag.pgroup %>
</p>

<p>
  <strong>Pcode:</strong>
  <%= @product_tag.pcode %>
</p>

<p>
  <strong>Pdescription:</strong>
  <%= @product_tag.pdescription %>
</p>

<p>
  <strong>Ptag:</strong>
  <%= @product_tag.ptag %>
</p>

<%= link_to 'Edit', edit_product_tag_path(@product_tag) %> |
<%= link_to 'Back', product_tags_path %>

app/views/tag_creation/Tag_setup.html.erb
<div class  = 'feild'>
<pre> <b>Set Tags through</b>     <%= radio_button_tag "reply", true, true %>Online    <%= radio_button_tag "reply", true, true %>Offline
</pre>
</div>
<pre>
<div class="container">     
     
      	<%= form_with(model: product_detail, local: true) do |form| %>
      <div class="field">
      <%= form.label :productcategory %>
      <%= form.Select(:productcategory, id: :product_detail_productcategory) %>
    </div>

  <div class="field">
    <%= form.label :productgroup %>
    <%= form.Select( :productgroup, id: :product_detail_productgroup) %>
  </div>

  <div class="field">
    <%= form.label :productcode %>
    <%= form.Select( :productcode, id: :product_detail_productcode) %>
  </div>

  <div class="field">
    <%= form.label :productdescription %>
    <%= form.Select( :productdescription, id: :product_detail_productdescription) %>
  </div>

  <% end %>
	 
     
</div>

</pre>

  <div align = "Right">

  	 <%= submit_tag("Save & Next") %>
  </div>